version: 0.0

Resources:
  - ViteApp:
      Type: Kubernetes::Manifest
      Properties:
        ClusterName: my-eks-cluster
        Namespace: default
        TaskDefinition: 
        deployment.yml --validate=false
        service.yml
