version: 0.2

phases:
  install:
    commands:
     - aws eks --region ap-south-1 update-kubeconfig --name ashokit-cluster13
     - aws_access_key_id = AKIARRRDCFDBLTRUS77A
     - aws_secret_access_key = ptNOi3+DtcZfFXhZ4tXlvMWzykHUeI8Br1g5Wd1C
  build:
    commands: 
      - kubectl apply -f deployment.yml --validate=false # Apply your Deployment configuration
      - kubectl apply -f services.yml--validate=false
