version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - kubectl apply -f Selvam3195/Project--React-app/deployment.yml # Apply your Deployment configuration
      - kubectl apply -f Selvam3195/Project--React-app/service.yml 
