version: 0.2

phases:
  install:
    commands:
  build:
    commands: 
     - aws eks update-kubeconfig --name ashokit-cluster14 --region ap-south-1
     - kubectl get nodes 
     - kubectl get deployments
     - kubectl apply -f deployment.yml --validate=false # Apply your Deployment configuration
     - kubectl apply -f services.yml--validate=false
