version: 0.2

phases:
  build:
    commands:
      - sudo kubectl apply -f deployment.yml # Apply your Deployment configuration
      - sudo kubectl apply -f service.yml # Apply your Service configuration
