version: 0.2

phases:
  build:
    commands:
      - sudo kubectl apply -f /home/ubuntudeployment.yml # Apply your Deployment configuration
      - sudo kubectl apply -f /home/ubuntu/service.yml # Apply your Service configuration
