version: 0.2

phases:
  build:
    commands:
      - sudo kubectl apply -f deployment.yml --validate=false # Apply your Deployment configuration
      - sudo kubectl apply -f service.yml --validate=false # Apply your Service configuration
