version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      # If you have any dependencies (like Vite), you can install them here
      # - npm install
  build:
    commands:
      - echo Build phase starting...
      # If using a tool like Vite, uncomment and customize below
      # - npm run build
      # For pure HTML/CSS/JS, you may skip actual build
  post_build:
    commands:
      - echo Build completed. Preparing artifacts...

artifacts:
  files:
    - index.html
    - vite.svg
    - assets/**

  discard-paths: no
