version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - kubectl apply -f /home/ubuntu/deployment.yml # Apply your Deployment configuration
      - kubectl apply -f /home/ubuntu/services.yml 
