version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - kubectl apply -f deployment.yml --validate=false # Apply your Deployment configuration
      - kubectl apply -f services.yml--validate=false
