version: 0.2

env:
  variables:
    IMAGE_TAG: latest
  # Optionally uncomment this if using environment variables in CodeBuild
  # parameter-store:
  #   AWS_DEFAULT_REGION: "/project/aws/default_region"
  #   ACCOUNT_ID: "/project/aws/account_id"
  #   REPO_NAME: "/project/ecr/repo_name"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=124355647640
      - REPO_NAME=react-app   # <-- replace with your ECR repo name
      - REGION=ap-south-1            # <-- replace with your AWS region
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 124355647640.dkr.ecr.ap-south-1.amazonaws.com
      - echo ECR login successful.

  build:
    commands:
      - echo Building the Docker image...
      - docker build https://github.com/Selvam3195/Project--React-app.git
      - docker tag react-app:latest 124355647640.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
      - echo Docker image tagged successfully.

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 124355647640.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
      - echo Docker image pushed to ECR successfully.

artifacts:
  files:
    - '**/*'
