version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - kubectl apply -f Project--React-app/deployment.yml # Apply your Deployment configuration
      - kubectl apply -f Project--React-app/services.yml 
