version: 0.2
phases:
  install:
      commands:
    - aws eks update-kubeconfig --name ashokit-cluster14 --region ap-south-1
     - kubectl get nodes 
     - kubectl get deployments
    - echo "Build phase complete."
    post_build:
    commands:
      - kubectl apply -f deployment.yml --validate=false # Apply your Deployment configuration
      - kubectl apply -f services.yml--validate=false
        - echo "Deployment phase complete."
