apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-manager-binding
subjects:
- kind: User
  name: 124355647640:role/service-role/AWSCodePipelineServiceRole-ap-south-1-myprojectex # Replace with the username associated with your IAM role in aws-auth ConfigMap
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
