apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codebuild-clusterrole-reader
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["get"]
