apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codebuild-clusterrole-reader-binding
subjects:
- kind: User  # Or 'Group' depending on how you've configured your aws-auth ConfigMap
  name: arn:aws:sts::124355647640:assumed-role/codebuild-app-2-service-role/AWSCodeBuild-51a39411-6620-46dd-9d2f-02733a1dd71f 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: codebuild-clusterrole-reader
  apiGroup: rbac.authorization.k8s.io
