apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codepipeline-deployer
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codepipeline-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codepipeline-deployer
subjects:
  - kind: User
    name: arn:aws:sts::123455567460:assumed-role/AWSCodePipelineServiceRole-ap-south-1-myprojectex
    apiGroup: rbac.authorization.k8s.io
