apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
labels:
    app: app
spec:
  replicas: 1 # You can increase this for more instances
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: react-app-container
          image: 124355647640.dkr.ecr.ap-south-1.amazonaws.com/reactproject:latest/reactapp:latest  # Replace with your image
          ports:
            - containerPort: 3000
