apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: vite-container
          image: 124355647640.dkr.ecr.ap-south-1.amazonaws.com/my-react-app
          ports:
            - containerPort: 80 
