apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app
  labels:
    app: vite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
        - name: vite-container
          image: 124355647640.dkr.ecr.ap-south-1.amazonaws.com/my-react-app
          ports:
            - containerPort: 80 
