apiVersion: v1
kind: Service
metadata:
  name: react
spec:
type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001 
      nodePort: 30000
~                                                                                                                                                             
~                                                                                                                                                             
~                           
